// Actividades oficiales tomadas de la columna "Actividad" del Índice Distrital.
(function () {
    'use strict';

    var actividades = [
        "Elaboración artesanal de productos de harina y derivados en el establecimiento, con venta directa y con o sin consumo en el local",
        "Elaboración de productos de harina y derivados por pedido, con atención al público, recojo o reparto de productos propios",
        "Elaboración de productos de harina y derivados por pedido, sin atención ni consumo en el establecimiento, con reparto de productos propios",
        "Confección, ajuste y reparación de prendas de vestir a medida, con atención al público",
        "Confección de prendas de vestir por encargo y en lotes limitados, con atención y entrega directa al cliente",
        "Confección de prendas de vestir por encargo, sin atención al público, con entrega de productos propios; sin producción en serie para terceros",
        "Impresión digital, fotocopiado, ploteo y acabados gráficos, con atención al público",
        "Impresión offset, serigrafía, sublimación o gran formato por encargo, con atención y entrega directa al cliente",
        "Impresión y producción gráfica por encargo, sin atención al público, con entrega de productos propios; sin producción industrial ni distribución mayorista",
        "Venta de vehículos automotores en sala de exhibición, sin taller",
        "Venta de vehículos automotores con sala de exhibición, patio de vehículos y área de entrega",
        "Lavado, limpieza y detallado de vehículos automotores",
        "Mantenimiento preventivo y servicio rápido de vehículos automotores (lubricación, neumáticos, baterías)",
        "Reparación mecánica, eléctrica, de carrocería y pintura de vehículos automotores",
        "Venta al por menor de partes, piezas y accesorios para vehículos automotores, sin instalación",
        "Venta de partes, piezas y accesorios para vehículos automotores con servicio de instalación",
        "Venta al por menor de motocicletas, partes y accesorios en sala de exhibición",
        "Mantenimiento y reparación de motocicletas",
        "Venta al por menor de alimentos, bebidas y artículos de uso diario mediante atención por mostrador",
        "Venta al por menor de alimentos, bebidas y artículos de uso diario mediante autoservicio, sin almacenamiento autónomo ni operación permanente de carga y descarga",
        "Venta al por menor de alimentos, bebidas y artículos de uso diario mediante autoservicio, con almacenamiento complementario y operación de carga y descarga",
        "Venta al por menor de alimentos mediante agrupación de puestos independientes dentro de un establecimiento común",
        "Venta temporal al por menor de alimentos y productos diversos mediante módulos desmontables en espacio público",
        "Venta al por menor de productos diversos, con atención directa al público",
        "Venta al por menor de productos diversos mediante exhibición organizada por marcas o departamentos en un solo establecimiento",
        "Agrupación de establecimientos comerciales independientes dentro de una edificación con circulación y servicios comunes",
        "Conjunto integrado de establecimientos comerciales con unidades principales, locales menores, circulación común y área común de alimentos",
        "Venta al por menor de pan, confitería y alimentos envasados, sin elaboración en el establecimiento",
        "Venta al por menor de frutas, verduras, lácteos y huevos, sin preparación ni consumo en el establecimiento",
        "Venta al por menor de carnes, pescados y productos refrigerados en tienda especializada",
        "Venta al por menor de bebidas envasadas en tienda especializada",
        "Venta al por menor de combustibles líquidos o gaseosos para vehículos mediante instalaciones de abastecimiento",
        "Venta al por menor de combustibles para vehículos con actividades complementarias de venta minorista, lavado o lubricación",
        "Venta al por menor de equipos informáticos, telefonía y accesorios, con atención directa al público",
        "Venta al por menor de equipos informáticos, de telecomunicaciones y software en tienda especializada",
        "Venta al por menor de equipos de sonido, video y accesorios, con atención directa al público",
        "Venta al por menor de equipos de sonido y video con exhibición y orientación técnica, sin taller de reparación",
        "Venta al por menor de telas, tejidos y artículos de mercería",
        "Venta al por menor de artículos de ferretería, pinturas y vidrios, sin almacén independiente",
        "Venta al por menor de artículos de ferretería y materiales de construcción, con almacenamiento complementario y despacho de productos propios; sin venta mayorista",
        "Venta al por menor de alfombras, cortinas, tapices y revestimientos para el hogar",
        "Venta al por menor de menaje, enseres y artículos de iluminación, con atención directa al público",
        "Venta al por menor de electrodomésticos y muebles en tienda especializada con exhibición",
        "Venta al por menor de útiles de escritorio, papelería y artículos de oficina, con atención directa al público",
        "Venta al por menor de libros, revistas y periódicos en librería",
        "Venta al por menor de artículos deportivos y bicicletas, sin armado ni mantenimiento en el establecimiento",
        "Venta al por menor de artículos deportivos y bicicletas, con armado y ajuste de productos nuevos; sin taller de reparación",
        "Venta al por menor de juegos y juguetes",
        "Venta al por menor de prendas de vestir, calzado y artículos de cuero, con atención directa al público",
        "Venta al por menor de prendas de vestir, calzado y artículos de cuero mediante exhibición y selección en un solo establecimiento",
        "Venta al por menor de medicamentos y productos farmacéuticos, con atención al público",
        "Venta al por menor de productos ortopédicos, material e instrumental médico",
        "Venta al por menor de productos naturales y suplementos, sin preparación ni consumo en el establecimiento",
        "Venta al por menor de perfumes, cosméticos y artículos de tocador",
        "Venta al por menor de flores, plantas y arreglos florales",
        "Venta al por menor de productos ópticos, con o sin medición visual",
        "Venta al por menor de artículos fotográficos, relojería y joyería",
        "Venta al por menor de animales de compañía, alimentos y accesorios, sin servicios veterinarios",
        "Venta al por menor de artículos de segunda mano y antigüedades",
        "Venta al por menor por internet o catálogo con punto de recojo, sin almacenamiento ni despacho desde el establecimiento",
        "Venta al por menor por internet con almacenamiento complementario y despacho de productos propios; sin almacén autónomo ni centro de distribución",
        "Estacionamiento vehicular en playa o edificio de estacionamientos",
        "Estación de recarga eléctrica para vehículos, bicicletas o scooters, con permanencia únicamente durante la recarga; sin taller de reparación",
        "Servicios postales con atención al público para admisión y entrega de envíos, sin centro de distribución",
        "Servicios de mensajería y courier con atención al público para recepción y entrega temporal de envíos",
        "Coordinación de servicios de mensajería desde oficina, sin atención al público ni recepción, acopio o almacenamiento de envíos",
        "Prestación de alojamiento temporal sin salones para eventos ni actividades complementarias de concurrencia pública",
        "Prestación de alojamiento temporal con actividades complementarias de alimentación, reuniones o eventos",
        "Preparación y expendio de bebidas no alcohólicas, postres y comidas ligeras, con o sin consumo en el establecimiento",
        "Preparación y expendio de comidas y bebidas con servicio a la mesa y consumo en el establecimiento",
        "Preparación y expendio de comidas de servicio rápido para consumo, recojo o reparto de productos propios, con o sin atención al público",
        "Expendio simultáneo de comidas y bebidas por varios operadores en un área común de consumo",
        "Preparación de comidas por encargo para eventos, sin consumo en el establecimiento, con despacho de productos propios",
        "Preparación y suministro de comidas a un cliente determinado mediante contrato, sin atención al público ni venta mayorista",
        "Expendio de bebidas alcohólicas con consumo en el establecimiento, sin pista de baile ni actividad principal de espectáculo",
        "Expendio de bebidas con música amplificada, pista de baile, presentaciones o canto recreativo",
        "Producción audiovisual en estudio o set de grabación",
        "Exhibición de obras cinematográficas y audiovisuales en una o más salas",
        "Grabación de sonido y edición musical en estudio",
        "Transmisión de radio con estudio y cabina de emisión",
        "Servicios de acceso a internet, telefonía y recargas, con atención al público (cabinas y locutorios)",
        "Operación técnica de telecomunicaciones, nodos y centros de datos, sin atención al público ni almacenamiento logístico",
        "Servicios de tecnología de la información y soporte informático en oficina",
        "Agencia bancaria, caja o cooperativa de ahorro y crédito",
        "Cajero automático o agente corresponsal en local independiente",
        "Servicios financieros no bancarios (arrendamiento financiero, factoraje, créditos) en oficina",
        "Seguros de vida en oficina",
        "Administración de fondos de pensiones en oficina",
        "Administración de mercados de valores en oficina",
        "Intermediación de valores y productos básicos (corredores de bolsa) en oficina",
        "Casa de cambio de moneda",
        "Compra, venta y arrendamiento de bienes inmuebles propios, en oficina o sala de ventas",
        "Corretaje y administración inmobiliaria en oficina",
        "Servicios notariales",
        "Servicios de abogacía y estudios jurídicos en oficina",
        "Servicios de contabilidad, auditoría y asesoría tributaria en oficina",
        "Oficinas administrativas o corporativas de empresas",
        "Oficinas compartidas o espacios de coworking",
        "Servicios de publicidad y agencias de medios en oficina",
        "Servicios de fotografía en estudio",
        "Servicios profesionales, científicos y técnicos en oficina (consultoría, servicios técnicos)",
        "Atención veterinaria ambulatoria en consultorio",
        "Clínica veterinaria con cirugía, hospitalización o alojamiento de animales",
        "Agencias de empleo y colocación de personal",
        "Agencias de viajes",
        "Operadores turísticos",
        "Servicios de seguridad privada en oficina, sin armería ni patio de vehículos",
        "Organización de convenciones, ferias y exposiciones en centro de eventos",
        "Sedes de la administración pública y de órganos de gobierno",
        "Oficinas de regulación, atención y facilitación de la administración pública",
        "Educación inicial (cuna, jardín)",
        "Educación primaria",
        "Educación secundaria de formación general",
        "Educación técnico-productiva en aula o taller, con prácticas formativas y sin producción comercial",
        "Centro de educación técnico-productiva con talleres y laboratorios",
        "Educación superior universitaria y no universitaria",
        "Enseñanza y entrenamiento deportivo en ambiente cerrado, sin cancha, campo, piscina o graderías",
        "Enseñanza y entrenamiento deportivo en instalación especializada con cancha, campo, piscina, coliseo o graderías",
        "Enseñanza artística y cultural en aula, taller o estudio, sin presentación de espectáculos al público",
        "Enseñanza de danza, teatro y artes escénicas en ambientes destinados al movimiento, ensayo o representación formativa",
        "Enseñanza complementaria y tutoría especializada (idiomas, reforzamiento, preparación)",
        "Formación religiosa",
        "Centro médico o policlínico de atención ambulatoria",
        "Clínica con internamiento",
        "Hospital",
        "Consultorio médico u odontológico individual",
        "Centro médico u odontológico con varios consultorios",
        "Servicios de enfermería, fisioterapia, podología y rehabilitación ambulatoria",
        "Laboratorio clínico y centro de toma de muestras",
        "Atención psicológica y de bienestar emocional en consultorio",
        "Servicios de salud ocupacional",
        "Casa de reposo con atención de enfermería",
        "Institución de atención en salud mental con internamiento",
        "Residencia para personas mayores o con discapacidad",
        "Albergue",
        "Centro de día para personas mayores o con discapacidad, sin alojamiento",
        "Cuidado diurno infantil sin alojamiento ni prestación de educación inicial escolarizada",
        "Asistencia social sin alojamiento (comedores, programas sociales)",
        "Producción de espectáculos y artes escénicas",
        "Espectáculos artísticos en vivo en sala o teatro",
        "Bibliotecas y archivos",
        "Museos y galerías de exhibición",
        "Agencia de apuestas deportivas sin máquinas de juego",
        "Sala de juegos de azar con máquinas tragamonedas o casino",
        "Operación de instalaciones cerradas para acondicionamiento físico, sin cancha, campo o piscina",
        "Operación y alquiler de instalaciones deportivas con cancha, campo o piscina",
        "Club deportivo",
        "Promoción y organización de competencias deportivas",
        "Parque temático o de atracciones",
        "Operación de espacios cerrados de recreación y entretenimiento infantil, familiar o temático, sin atracciones mecánicas o acuáticas propias de un parque de atracciones",
        "Asociaciones, colegios y gremios profesionales",
        "Organizaciones religiosas (templos y locales de culto)",
        "Reparación de calzado y artículos de cuero",
        "Reparación de bicicletas, relojes, electrodomésticos menores y otros efectos personales",
        "Recepción y entrega de prendas para lavado realizado fuera del establecimiento, sin equipos de lavado o secado",
        "Lavandería de autoservicio o con equipos de lavado, secado o limpieza en seco en el establecimiento",
        "Servicios de cuidado capilar, barbería, manicure y tratamientos estéticos no médicos, con atención al público",
        "Servicios de relajación, masaje no terapéutico y spa, sin procedimientos médicos",
        "Servicios personales no clasificados en otra parte, con atención directa y sin procedimientos médicos",
        "Servicios de higiene, cuidado estético y acondicionamiento de animales de compañía",
        "Servicios de entrenamiento y modificación de conducta de animales de compañía",
        "Organizaciones internacionales y representaciones diplomáticas"
    ];

    var catalogo = window.datosBuscadorGiros && window.datosBuscadorGiros.giros;
    if (!Array.isArray(catalogo) || catalogo.length !== actividades.length) return;

    catalogo.forEach(function (giro, indice) {
        giro.giro = actividades[indice];
    });

    var porCodigo = {};
    catalogo.forEach(function (giro) { porCodigo[giro.cod_giro] = giro.giro; });

    if (Array.isArray(window.datosActividadesIndice)) {
        window.datosActividadesIndice.forEach(function (giro) {
            if (porCodigo[giro.COD_GIRO]) giro.ACTIVIDAD = porCodigo[giro.COD_GIRO];
        });
    }

    (window.datosActividadesZRE || []).forEach(function (giro) {
        var numero = String(giro['N°'] || '').padStart(2, '0');
        var actividad = porCodigo[String(giro.CLASE || '').trim() + '-' + numero];
        if (actividad) giro.ACTIVIDAD = actividad;
    });
})();
